replicaCount: 1

image:
  repository: 394422659307.dkr.ecr.eu-west-1.amazonaws.com/gitops
  tag: 5424dde30716c47d459600845cae9e94d1f1ef4e

service:
  type: LoadBalancer
  port: 80

containerPort: 8080