apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-app-config
  namespace: gitops-app
data:
  application.properties: |
    spring.application.name=gitops-app
    server.port=8080
    spring.profiles.active=prod
