name: Build and Push to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'Dockerfile'
      - '.github/workflows/**'

permissions:
  id-token: write
  contents: read

env:
  ECR_REPOSITORY: gitops
  AWS_REGION: eu-west-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Application
        run: mvn clean package -DskipTests

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::394422659307:role/gitPushECR
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: docker build -t gitops .

      - name: Tag Image
        run: |
          docker tag gitops:latest \
          394422659307.dkr.ecr.eu-west-1.amazonaws.com/gitops:${{ github.sha }}

      - name: Push Image
        run: |
          docker push \
          394422659307.dkr.ecr.eu-west-1.amazonaws.com/gitops:${{ github.sha }}